BEGIN;
UPDATE Settings SET value='14.06' WHERE name='version';
UPDATE Settings SET value='0' WHERE name='subVersion';
ALTER TABLE users ALTER COLUMN zip TYPE CHARACTER VARYING(128) ;
ALTER TABLE users ALTER COLUMN kind TYPE CHARACTER VARYING(128) ;
ALTER TABLE users ALTER COLUMN phone TYPE CHARACTER VARYING(128) ;
COMMIT;
